# Generated by Django 5.2.16 on 2026-07-26 13:03

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='название')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('coordinator', 'Координатор'), ('tutor', 'Тьютор'), ('parent', 'Родитель')], max_length=20, verbose_name='роль')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='телефон')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.organization', verbose_name='организация')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
            ],
            options={
                'verbose_name': 'координатор',
                'verbose_name_plural': 'координаторы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
            managers=[
                ('objects', core.models.CoordinatorManager()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
            ],
            options={
                'verbose_name': 'родитель',
                'verbose_name_plural': 'родители',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
            managers=[
                ('objects', core.models.ParentManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
            ],
            options={
                'verbose_name': 'тьютор',
                'verbose_name_plural': 'тьюторы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
            managers=[
                ('objects', core.models.TutorManager()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('grade', models.CharField(blank=True, max_length=10, verbose_name='класс')),
                ('language', models.CharField(blank=True, max_length=50, verbose_name='язык обучения')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата начала')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='core.organization', verbose_name='организация')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('grade', models.CharField(max_length=10, verbose_name='класс')),
                ('language', models.CharField(blank=True, max_length=50, verbose_name='язык обучения')),
                ('svc_category', models.CharField(blank=True, max_length=100, verbose_name='категория SVC')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='телефон')),
                ('parent_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО родителя')),
                ('parent_phone', models.CharField(blank=True, max_length=32, verbose_name='телефон родителя')),
                ('parent_email', models.EmailField(blank=True, max_length=254, verbose_name='email родителя')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to=settings.AUTH_USER_MODEL, verbose_name='кем создан')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.organization', verbose_name='организация')),
            ],
            options={
                'verbose_name': 'ученик',
                'verbose_name_plural': 'ученики',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ParentInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email родителя')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='хеш токена')),
                ('expires_at', models.DateTimeField(verbose_name='действует до')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='принято')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invites', to=settings.AUTH_USER_MODEL, verbose_name='кем создано')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_invites', to='core.student', verbose_name='ученик')),
            ],
            options={
                'verbose_name': 'приглашение родителя',
                'verbose_name_plural': 'приглашения родителей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals', to='core.group', verbose_name='группа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='core.student', verbose_name='ученик')),
            ],
            options={
                'verbose_name': 'журнал',
                'verbose_name_plural': 'журналы',
                'ordering': ['student__full_name', 'subject__name'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='groups', to='core.student', verbose_name='ученики'),
        ),
        migrations.AddField(
            model_name='user',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='core.student', verbose_name='дети'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='core.organization', verbose_name='организация')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('time', models.TimeField(verbose_name='время')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий (изменения, переносы)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_entries', to=settings.AUTH_USER_MODEL, verbose_name='кем создано')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='core.group', verbose_name='группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='core.subject', verbose_name='предмет')),
            ],
            options={
                'verbose_name': 'занятие в расписании',
                'verbose_name_plural': 'расписание',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('link', models.URLField(blank=True, verbose_name='ссылка')),
                ('grade', models.CharField(blank=True, max_length=10, verbose_name='класс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='core.subject', verbose_name='предмет')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LessonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата урока')),
                ('topic', models.CharField(max_length=255, verbose_name='тема урока')),
                ('attended', models.BooleanField(default=True, verbose_name='присутствовал')),
                ('lesson_grade', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='оценка за урок')),
                ('homework_assigned', models.BooleanField(default=False, verbose_name='задано ДЗ')),
                ('homework_grade', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='оценка за ДЗ')),
                ('feedback', models.TextField(blank=True, verbose_name='фидбек по ученику')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lesson_reports', to=settings.AUTH_USER_MODEL, verbose_name='кем создан')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_reports', to='core.journal', verbose_name='журнал')),
                ('schedule_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_reports', to='core.scheduleentry', verbose_name='занятие по расписанию')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_reports', to='core.subject', verbose_name='предмет')),
            ],
            options={
                'verbose_name': 'запись урока',
                'verbose_name_plural': 'записи уроков',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='journal',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='core.subject', verbose_name='предмет'),
        ),
        migrations.AddField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(related_name='groups', to='core.subject', verbose_name='предметы'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('test_type', models.CharField(choices=[('entry', 'Входной (диагностический)'), ('midterm', 'Промежуточный'), ('final', 'Итоговый')], max_length=20, verbose_name='тип')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата')),
                ('max_score', models.PositiveSmallIntegerField(default=100, verbose_name='максимальный балл')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.group', verbose_name='группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='core.subject', verbose_name='предмет')),
            ],
            options={
                'verbose_name': 'тест',
                'verbose_name_plural': 'тесты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='балл')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_results', to=settings.AUTH_USER_MODEL, verbose_name='кем внесён')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='core.journal', verbose_name='журнал')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.test', verbose_name='тест')),
            ],
            options={
                'verbose_name': 'результат теста',
                'verbose_name_plural': 'результаты тестов',
                'ordering': ['-test__date'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutor_groups', to='core.tutor', verbose_name='тьютор'),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.UniqueConstraint(fields=('student', 'subject'), name='unique_journal_per_student_subject'),
        ),
        migrations.AddConstraint(
            model_name='testresult',
            constraint=models.UniqueConstraint(fields=('journal', 'test'), name='unique_result_per_journal_test'),
        ),
    ]
